---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: heading
  label: Pages
- type: document
  path: content/nl/home.md
  label: Home
- type: document
  path: content/nl/project-overzicht.md
  label: Projecten overzicht
- type: document
  path: content/nl/team.md
  label: Team
- type: heading
  label: Collections
- type: directory
  path: content/nl/projecten
  label: Projecten
  create: documents
  match: "**/*"
  templates:
  - project
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: yarn
  preview_docker_image: forestryio/node:14
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn dev
